services:
  postgres_driven_ops_db:
    image: postgres
    container_name: postgres_driven_ops_db
    restart: always
    ports:
      - 1234:5432
    env_file:
      -back-end/.env
    volumes:
      - pg:/var/lib/postgresql/data

  node_driven_ops_app:
    container_name: node_driven_ops_app
    buid: ./back-end
    ports: 
      - 5000:5000
    depends_on:
      - postgres_driven_ops_db
    env_file:
      - back-end/.env

  react_driven_ops_app:
    container_name: react_driven_ops_app
    build: ./front-end
    volumes:
      - build_react:/var/www/html

  nginx_driven_ops_app:
    container_name: nginx_driven_ops_app
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres_driven_ops_db4
      - node_driven_ops_app
      - react_driven_ops_app

volumes:
  pg_driven_ops_db:
  build_react:
